routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */



Route::get('/', 'IndexController@show')->name('bloglist');
Route::resource('blogs', 'blogController');
Auth::routes();

Route::get('/facadeex', function() {
    return TestFacades::testingFacades();
});

Route::Group(['prefix' => env('BACKEND_PATH'), 'middleware' => ['auth', 'activation']], function () {
    Route::get('/admin', 'HomeController@index')->name('home');
    Route::resource('blogs', 'blogController');
    Route::resource('category', 'categoryController');


    // Clear Cache
    Route::get('/cache-clear', function () {
        Artisan::call('cache:clear');
        Artisan::call('view:clear');        
    })->name('cacheClear');
    
});

app/Blog.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;
class Blog extends Model
{
    protected $fillable = [
        'category_id','title', 'content'
    ];
}

app/Http/Controllers/blogController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Blog;
use Illuminate\Http\Request;
use Auth;
use Image;
use Helper;

class blogController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $blogs = Blog::select('categories.title as category', 'blogs.*')
                        ->leftJoin('categories', 'blogs.category_id', '=', 'categories.id')
                        ->orderby('id', 'desc')->get();
        return view('admin.blogs.index', compact('blogs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $category = Category::orderby('id', 'desc')->get();
        return view('admin.blogs.create', compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {

        $this->validate($request, [
            'title' => 'required',
            'content' => 'required'
        ]);
        $post = new Blog;
        $post->category_id = $request->category_id;
        $post->user_id = Auth::id();
        $post->title = $request->title;
        $post->slug = str_slug($request->slug);
        $post->content = Helper::checkEmpty($request->content);
        $filename = '';
        if (!empty($request->file('image'))) {
            $filename = Helper::uploadImage($request->file('image'));
        }
        $post->image = $filename;
        $post->save();
        return redirect()->route('blogs.index')
                        ->with('success', 'blogs created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Blog $blog
     * @return \Illuminate\Http\Response
     */
    public function show(Blog $blog) {
        return view('admin.blogs.show', compact('blog'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Blog $blog
     * @return \Illuminate\Http\Response
     */
    public function edit(Blog $blog) {
        $category = Category::orderby('id', 'desc')->get();
        return view('admin.blogs.edit', compact('blog', 'category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Blog $blog
     * @return \Illuminate\Http\Response
     */
    public function update($id, Request $request) {
        $this->validate($request, [
            'title' => 'required',
            'content' => 'required'
        ]);
        $post = Blog::find($id);
        $post->category_id = $request->category_id;
        $post->user_id = Auth::id();
        $post->title = $request->title;
        $post->slug = str_slug($request->slug);
        $post->content = Helper::checkEmpty($request->content);
        $filename = '';
        if (!empty($request->file('image'))) {
            $image = $request->file('image');
            $filename = time() . '.' . $image->getClientOriginalExtension();
            $location = public_path('public/images/') . $filename;
            Image::make($image)->save($location);
        } else {
            $filename = $request->old_image;
        }
        $post->image = $filename;
        $post->save();
        return redirect()->route('blogs.index')
                        ->with('success', 'blogs updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Blog $blog
     * @return \Illuminate\Http\Response
     */
    public function destroy(Blog $blog) {
        $blog->delete();
        return redirect()->route('blogs.index')
                        ->with('success', 'Blog deleted successfully');
    }

}

resources/views/admin/blogs/create.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h5>Add New Blogs</h5>
                    </div>
                    <br />
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('blogs.index') }}"> Back</a>
                    </div>
                     <br />
                </div>
            </div>
            @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <form action="{{ route('blogs.store') }}" method="POST" enctype="multipart/form-data">
                @csrf

                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Category:</strong>
                            <select class="form-control" name="category_id">
                                <option value="">--Select -- </option>
                                @if(!empty($category))
                                @foreach ($category as $cat)
                                <option value="{{ $cat->id }}"> {{ $cat->title }} </option>
                                @endforeach
                                @endif
                            </select>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Title:</strong>
                            <input type="text" name="title" class="form-control" placeholder="title">
                        </div>
                    </div>
                    
                      <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Title:</strong>
                            <input type="file" name="image" class="form-control" placeholder="Image">
                        </div>
                    </div>
                  
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Content:</strong>
                            <textarea class="form-control" style="height:150px" name="content" placeholder="Content"></textarea>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/admin/blogs/edit.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h2>Edit Blogs</h2>
                    </div>
                    <br />
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('blogs.index') }}"> Back</a>
                    </div>
                    <br />
                </div>
            </div>
            @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <form action="{{ route('blogs.update',$blog->id) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Category:</strong>
                            <select class="form-control" name="category_id">
                                <option value="">--Select -- </option>
                                @if(!empty($category))
                                @foreach ($category as $cat)
                                <option @if($blog->category_id==$cat->id) selected="selected" @endif value="{{ $cat->id }}"> {{ $cat->title }} </option>
                                @endforeach
                                @endif
                            </select>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Title:</strong>
                            <input type="text" name="title" value="{{ $blog->title }}" class="form-control" placeholder="Name">
                        </div>
                    </div>
                    
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Title:</strong>
                            <input type="file" name="image" class="form-control" placeholder="Image">
                            @if(!empty($blog->image))
                            <img style="height:100px;" src="{{ Helper::ImageURL($blog->image)}}">
                            <input type="hidden" name="old_image" value="{{ $blog->image }}">
                            @else
                            <div class="fakeimg" style="height:100px;">Image</div>
                            @endif
                        </div>
                    </div>
                    
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Content:</strong>
                            <textarea class="form-control" style="height:150px" name="content" placeholder="Detail">{{ $blog->content }}</textarea>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/admin/blogs/index.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h5> Blogs </h5>
                    </div>
                    <br />
                    <div class="pull-right">
                        <a class="btn btn-success" href="{{ route('blogs.create') }}"> Create New Blog</a>
                    </div>
                    <br />
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ url('/admin') }}"> Back</a>
                    </div>
                    <br />
                    <br />
                </div>
            </div>
            @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
            @endif
            <table class="table table-bordered w3-table-all w3-card-4">
                <tr>
                    <th>Title</th>
                    <th>Image</th>
                    <th>Category</th>
                    <th>Content</th>
                    <th width="280px">Action</th>
                </tr>
                @foreach ($blogs as $blog)
                <tr>
                    <td>{{ $blog->title }}</td>
                    <td>
                    @if(!empty($blog->image))
                            <img style="height:50px;" src="{{ Helper::ImageURL($blog->image)}}">
                            @else
                            <div class="fakeimg" style="height:50px;">Image</div>
                            @endif
                    </td>
                    <td>{{ $blog->category }}</td>
                    <td>{{ Helper::word_teaser($blog->content,15).'...' }}</td>
                    <td>
                        <form action="{{ route('blogs.destroy',$blog->id) }}" method="POST">
                            <a class="btn btn-info" href="{{ route('blogs.show',$blog->id) }}">Show</a>
                            <a class="btn btn-primary" href="{{ route('blogs.edit',$blog->id) }}">Edit</a>
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </table>

        </div></div></div>

@endsection

resources/views/admin/blogs/layout.blade.php
<!DOCTYPE html>
<html>
<head>
<title>Laravel 5.8 CRUD Generator Application</title>
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
</head>
<body>
<div class="container">
@yield('content')
</div>
</body>
</html>

resources/views/admin/blogs/show.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h2> Show Blogs</h2>
                    </div>
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('blogs.index') }}"> Back</a>
                    </div>
                     <br />
                </div>
            </div>
            <div class="row">
                <br />
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Title:</strong>
                        {{ $blog->title }}
                    </div>
                </div>
                
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Title:</strong>
                        {{ Helper::getCategory($blog->category_id) }}
                    </div>
                </div>
                
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Image:</strong>
                            @if(!empty($blog->image))
                            <img style="height:100px;" src="{{ Helper::ImageURL($blog->image)}}">
                            <input type="hidden" name="old_image" value="{{ $blog->image }}">
                            @else
                            <div class="fakeimg" style="height:100px;">Image</div>
                            @endif
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Content:</strong>
                        {{ $blog->content }}
                    </div>
                </div>
            </div></div></div></div>
@endsection