routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */



Route::get('/', 'IndexController@show')->name('bloglist');
Route::resource('blogs', 'blogController');
Auth::routes();

Route::get('/facadeex', function() {
    return TestFacades::testingFacades();
});

Route::Group(['prefix' => env('BACKEND_PATH'), 'middleware' => ['auth', 'activation']], function () {
    Route::get('/admin', 'HomeController@index')->name('home');
    Route::resource('blogs', 'blogController');
    Route::resource('category', 'categoryController');


    // Clear Cache
    Route::get('/cache-clear', function () {
        Artisan::call('cache:clear');
        Artisan::call('view:clear');        
    })->name('cacheClear');
    
});

app/Blog.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;
class Blog extends Model
{
    protected $fillable = [
        'category_id','title', 'content'
    ];
}

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
     protected $fillable = [
        'title'
    ];
}

app/Http/Controllers/blogController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Blog;
use Illuminate\Http\Request;
use Auth;
use Image;
use Helper;

class blogController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $blogs = Blog::select('categories.title as category', 'blogs.*')
                        ->leftJoin('categories', 'blogs.category_id', '=', 'categories.id')
                        ->orderby('id', 'desc')->get();
        return view('admin.blogs.index', compact('blogs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $category = Category::orderby('id', 'desc')->get();
        return view('admin.blogs.create', compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {

        $this->validate($request, [
            'title' => 'required',
            'content' => 'required'
        ]);
        $post = new Blog;
        $post->category_id = $request->category_id;
        $post->user_id = Auth::id();
        $post->title = $request->title;
        $post->slug = str_slug($request->slug);
        $post->content = Helper::checkEmpty($request->content);
        $filename = '';
        if (!empty($request->file('image'))) {
            $filename = Helper::uploadImage($request->file('image'));
        }
        $post->image = $filename;
        $post->save();
        return redirect()->route('blogs.index')
                        ->with('success', 'blogs created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Blog $blog
     * @return \Illuminate\Http\Response
     */
    public function show(Blog $blog) {
        return view('admin.blogs.show', compact('blog'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Blog $blog
     * @return \Illuminate\Http\Response
     */
    public function edit(Blog $blog) {
        $category = Category::orderby('id', 'desc')->get();
        return view('admin.blogs.edit', compact('blog', 'category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Blog $blog
     * @return \Illuminate\Http\Response
     */
    public function update($id, Request $request) {
        $this->validate($request, [
            'title' => 'required',
            'content' => 'required'
        ]);
        $post = Blog::find($id);
        $post->category_id = $request->category_id;
        $post->user_id = Auth::id();
        $post->title = $request->title;
        $post->slug = str_slug($request->slug);
        $post->content = Helper::checkEmpty($request->content);
        $filename = '';
        if (!empty($request->file('image'))) {
            $image = $request->file('image');
            $filename = time() . '.' . $image->getClientOriginalExtension();
            $location = public_path('public/images/') . $filename;
            Image::make($image)->save($location);
        } else {
            $filename = $request->old_image;
        }
        $post->image = $filename;
        $post->save();
        return redirect()->route('blogs.index')
                        ->with('success', 'blogs updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Blog $blog
     * @return \Illuminate\Http\Response
     */
    public function destroy(Blog $blog) {
        $blog->delete();
        return redirect()->route('blogs.index')
                        ->with('success', 'Blog deleted successfully');
    }

}

app/Http/Controllers/categoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;

class categoryController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        //
        $category = Category::orderby('id', 'desc')->get();
        return view('admin.blogs.category.index', compact('category'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        //
        return view('admin.blogs.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        //
        $request->validate([
            'title' => 'required'
        ]);
        Category::create($request->all());
        return redirect()->route('category.index')
                        ->with('success', 'Category created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        //
        
         $category = Category::find($id);
         return view('admin.blogs.category.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        //
        $category = Category::find($id);
        return view('admin.blogs.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        //
        $cat = Category::find($id);
         $request->validate([           
            'title' => 'required'           
        ]);
        $cat->update($request->all());
        return redirect()->route('category.index')
                        ->with('success', 'Category updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        //Delete record
        $Cat = Category::find($id);
        if (!empty($Cat)) {
            $Cat->delete();
        }
        return redirect()->route('category.index')
                        ->with('success', 'Blog deleted successfully');
    }

}

resources/views/admin/blogs/category/create.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h5>Add New Category</h5>
                    </div>
                    <br />
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('category.index') }}"> Back</a>
                    </div>
                    <br />
                </div>
            </div>
            @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <form action="{{ route('category.store') }}" method="POST">
                @csrf
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Title:</strong>
                            <input type="text" name="title" class="form-control" placeholder="title">
                        </div>
                    </div>                    
                    <div class="col-xs-12 col-sm-3 col-md-3">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>  
</div>        
@endsection

resources/views/admin/blogs/category/edit.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h2>Edit Blogs</h2>
                    </div>
                    <br />
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('blogs.index') }}"> Back</a>
                    </div>
                    <br />
                </div>
            </div>
            @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <form action="{{ route('category.update',$category->id) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="row">                   
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Title:</strong>
                            <input type="text" name="title" value="{{ $category->title }}" class="form-control" placeholder="Name">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-3 col-md-3">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                    
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/admin/blogs/category/index.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h5> Blog Category</h5>
                    </div>
                    <br />
                    <div class="pull-right">
                        <a class="btn btn-success" href="{{ route('category.create') }}"> Create New Category</a>
                    </div>
                    <br />
                   
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ url('/admin') }}"> Back</a>
                    </div>
                    <br />
                    
                </div>
            </div>
            @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
            @endif
            <table class="table table-bordered w3-table-all w3-card-4">
                <tr>
                    <th>Title</th>
                   
                    <th width="280px">Action</th>
                </tr>
                @if(!empty($category))
                @foreach ($category as $cat)
                <tr>
                    <td>{{ $cat->title }}</td>        
                    <td>
                        <form action="{{ route('category.destroy',$cat->id) }}" method="POST">
                            <a class="btn btn-info" href="{{ route('category.show',$cat->id) }}">Show</a>
                            <a class="btn btn-primary" href="{{ route('category.edit',$cat->id) }}">Edit</a>
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </td>
                </tr>
                @endforeach
                @endif
            </table>
        </div></div>
    @endsection

resources/views/admin/blogs/category/show.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h4> Show Category</h4>
                    </div>
                    <br />
                    <div class="pull-right">
                        <a class="btn btn-primary" href="{{ route('category.index') }}"> Back</a>
                    </div>
                    <br />
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Title:</strong>
                        {{ $category->title }}
                    </div>
                </div>
                
            </div></div></div></div>
@endsection